### ISSUE TITLE
AggregateExecutorTests causing JVM core dump

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#5] opened 2020-03-31 20:10 UTC
This seems to be happening across a range of different tests within the `AggregateExecutorTest` suite.

Here is an example of one of the errors:

```
[INFO] a.c.pathling.query.AggregateExecutor - Received $aggregate request: aggregations=[count()] groupings=[item.sequence.first() + 1] filters=[]
[INFO] a.c.pathling.query.SearchExecutor - Received search request: filters=[(item.sequence.first() + 1) = 2]
[INFO] a.c.pathling.query.SearchExecutor - Retrieving search results (1-100)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0xa) at pc=0x000000010b00e41c, pid=92243, tid=0x0000000000002803
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# v  ~StubRoutines::jbyte_disjoint_arraycopy
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/xxxxx/Code/pathling/fhir-server/hs_err_pid92243.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

This can be reproduced using OpenJDK 8u242 on a Mac.

**Comment by johngrimes** [comment] 2020-04-20 00:52
@piotrszul Any update on this one?

One other thing I thought of trying is Oracle JDK vs OpenJDK...

Did you manage to narrow it down to the line within our code that triggers the core dump?

**Comment by johngrimes** [comment] 2020-04-20 01:31
Another thing to do is remove the Bundles functionality from the encoders, along with the associated tests (#37).

No point trying to fix some obscure problem in an area of the encoders that we don't even use.

**Comment by piotrszul** [comment] 2020-04-20 04:08
@johngrimes 
No I have not found this line yet and it might and might not be in our code.
I have written some test that isolate encoders and the encoding/decoding of fhir 'Beans' to ans from UnsafeRecord.  By themselves they do not seem to be causing core dumps, but I did find two issues with decode/encode not being identity. 

In particular 
- for `InstantType` - this is an actual bug as the decoder does not compensate for the fact that Spark stores timestamps with microseconds precision., so decoded instants are way in the future. (I have a fix for this one)
- for quantities - the way we store it now  always converts precision to 4 decimal places. This is agains the specification which says that  precision should be preserved and 1.0000 is different than 1.00.   For currency amounts it adds unnecessary 0s e.g.  22.22 becomes 22.2000 and for some high precision values  e.g. from observations drops some decimal places e.g.  0.0232323232 -> 0.0233. Not sure how bit of an issue this is. 

I do not believe this is a VM issue - because it pops us in the code that uses Unsafe direct access to RAM, so changing the VM is most likely have not impact or will just mask the issue.
I am not sure about the bundles ... but I do not think my tests are using them.

I was actually able to catch an exception rather than core dump, in a case when the garbage data read from somewhere are used to initialize a Period type, which cannot parse the garbage string it receives.
So it is most likely an issues with Encoders most likely with deserialization and some mixup of the in the thungsten encoded data.  It may by related to decoding choiceType.
It also may only be a problem when reading from parquet (i.e. I was not able to reproduce this issue for dataset converted from JSON (with the parser)). So I am guessing it's either in our code or possibly Spark.

**Comment by johngrimes** [comment] 2020-04-20 04:16
Great, sounds like we are getting closer!

If you do have failing tests that you can push up on to a branch, that would be helpful.

**Comment by piotrszul** [comment] 2020-04-21 09:05
Hi @johngrimes  I think (and I am quite confident) that I have found the issue.
You actually had a good intuition that the schema of the test data may not be compatible with the encoder we use while testing.

But actually the issue that the schema is likely not compatible between any two VM runs.

It's becasue  the schema for choices is not deterministic: the oder of fields semi-randomly set by HashSet based default implementation of hashCode() in IBase i.e. memory handle of each childType of the choice. And the handle may be different in every VM and thus the schema for choices differs as well.

I have sorted the fields by typeName and now it seems to be working.

**Comment by johngrimes** [comment] 2020-04-21 22:00
Nice work @piotrszul, I'm so glad to finally crack this one!

I pulled down your commits on `spike/5`, rebased onto master and it works for me!

I am going to create a new branch `release/1.0.5` and I am going to start collecting this and a few other bug fixes into a pull request and try to get it green.

**Closed** 2020-04-23 05:16 UTC
Labels: bug
